### ISSUE TITLE
Blast bricks have no recipe

### ISSUE THREAD

**Issue by Turmfalke2** [Blood-Asp/IndustryGigant#2]
hi,
The 27 blast bricks for the wrought iron quest have no recipe in NEI.

**Comment by Turmfalke2** [comment]
Crafting 27 reinforced blast bricks gave me a quest update message, but it still says it wants 27 normal ones.

**Comment by Blood-Asp** [comment]
quest will be changed next update.

**Comment by Turmfalke2** [comment]
Updated to 8633d7c0, now the quest wants reinforced blast bricks, but the reinforced blast bricks have lost their recipe.

**Comment by Blood-Asp** [comment]
the finally approved build on curse has that fixed...
And also fixed the file on OneDrive.

**Comment by Turmfalke2** [comment]
How is that build different from the repo here? Doing just a git pull is easier than having to search for a working curse downloader.

**Comment by Blood-Asp** [comment]
Forgot to push latest update. Now it is fine.

**Comment by Turmfalke2** [comment]
Could you maybe tag the commits with version used for OneDrive/curse?

**Comment by Blood-Asp** [comment]
You should be able to see that with the changelog textfile inside. I start writing the next version after updating the pack.

**Comment by Turmfalke2** [comment]
I am not sure I am following your train of thought. How is searching with git blame through Changelog.txt for the correct commit easier than just doing git checkout v0.4.0?
You are aware how git tags work? https://www.kernel.org/pub/software/scm/git/docs/git-tag.html
