### ISSUE TITLE
Liquid vs Molten redstone

### ISSUE THREAD

**Issue by Quadrai** [Blood-Asp/IndustryGigant#4]
You can make Red Alloy Ingots with 4 redstone + 1 copper in the smeltery. Redstone melts to "Molten Redstone". However there's also a couple recipes for Red Alloy Ingots with "Liquid Redstone" (+ Iron or copper or aluminium). The "Liquid Redstone" is unobtainable.

Looks like "Liquid Restone" needs to be unified to "Molten Redstone" or the recipes need to be removed.

**Comment by Blood-Asp** [comment]
Disabled the unneeded smeltery recipes.
