### ISSUE TITLE
Large boiler quest requires an input bus?

### ISSUE THREAD

**Issue by Turmfalke2** [Blood-Asp/IndustryGigant#8]
hi,
Why would an boiler have an input bus?

**Comment by Blood-Asp** [comment]
Hmm, required is maybe wrong... But it can be used as input for solid fuels.

**Comment by Turmfalke2** [comment]
A bus? isn't the bus for eu? and the hatch for items?

**Comment by Blood-Asp** [comment]
The hatch is for fluids, the bus is for items.
For EU is the Energy Hatch or Dynamo hatch.
Look at the tooltip of the large boiler.

**Comment by Turmfalke2** [comment]
ok, nvm apparently I did not remember this the correct way
