### ISSUE TITLE
Molten Lead + Molten Antimony

### ISSUE THREAD

**Issue by Turmfalke2** [Blood-Asp/IndustryGigant#9]
hi,
I can't alloy battery alloy in the tinkers smeltery. Somehow the liquids don't mix.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/IndustryGigantCore/commit/aea913ab99c42ba9f87456f272e24d6468595934

**Comment by Turmfalke2** [comment]
thank you, downloading.

**Comment by Ormusn2o** [comment]
Red alloy still does not work in 0.5 .  Battery alloy is fixed.

**Comment by Ormusn2o** [comment]
Disregard my comment, im retarded, red alloy works.
